name: ClusterFuzzLite

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions: read-all


jobs:
  fuzzing:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Override for this step to allow writing crash artifacts
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Check out the repo
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
        with:
          go-version: '1.23'

      - name: Install Dependencies
        run: go mod download

      - name: Run Fuzz Tests
        run: |
          go test -fuzz=. -fuzztime=60s

      - name: Upload Crash Artifacts
        if: failure()
        uses: actions/upload-artifact@604373da6381bf24206979c74d06a550515601b9
        with:
          name: fuzz-crashers
          path: fuzz_crashers/
