name: ClusterFuzzLite

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions: read-all


jobs:
  fuzzing:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Override for this step to allow writing crash artifacts
    steps:
      - name: Check out the repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
        with:
          go-version: '1.23'

      - name: Install Dependencies
        run: go mod download

      - name: Run Fuzz Tests
        run: |
          go test -fuzz=. -fuzztime=60s

      - name: Upload Crash Artifacts
        if: failure()
        uses: actions/upload-artifact@c24449f33cd45d4826c6702db7e49f7cdb9b551d
        with:
          name: fuzz-crashers
          path: fuzz_crashers/
